name: CI/CD Deploy to Azure VM

on:
  push:
    branches: [ master ]  # Adjust if your default branch is different

jobs:
  deploy:
    name: Deploy to Azure VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Rsync project to Azure VM
        run: |
          rsync -avz --delete --exclude='.git*' ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/${{ secrets.USERNAME }}/ocr-clickfix-api

      - name: Setup venv, install dependencies, restart service
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd /home/${{ secrets.USERNAME }}/ocr-clickfix-api

            # Remove old venv if it exists
            if [ -d "venv" ]; then
              rm -rf venv
            fi

            # Create and activate new virtualenv
            python3 -m venv venv
            source venv/bin/activate

            # Upgrade pip and install requirements
            # pip install --upgrade pip
            pip install -r requirements.txt

            # Restart Gunicorn
            sudo systemctl restart ${{ secrets.SERVICE_NAME }}
            sudo systemctl status ${{ secrets.SERVICE_NAME }} --no-pager
          EOF
