name: 🚀 Deploy to Azure VM

on:
  push:
    branches:
      - master  # new update

jobs:
  deploy:
    name: Deploy Flask API to Azure VM
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v3

    - name: 🧩 Install SSH Key
      run: |
        echo "${{ secrets.SSH_KEY }}" > key.pem
        chmod 600 key.pem

    - name: 📡 Deploy Code via rsync
      run: |
        rsync -avz --delete --exclude '.git*' -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/${{ secrets.USERNAME }}/ocr-clickfix-api

    - name: 🔧 Set up Python & Restart Gunicorn
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
        set -e
        cd ~/ocr-clickfix-api
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        sudo systemctl restart clickfix
        EOF
