name: Deploy ClickFix API

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to VM
      run: |
        rsync -avz --delete --exclude='.git*' ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/ocr-clickfix-api

    - name: Deploy on VM
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/${{ secrets.SSH_USER }}/ocr-clickfix-api

          # Setup venv if not exists
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi

          source venv/bin/activate

          # Always reinstall in case of updates
          pip install --upgrade pip
          pip install -r requirements.txt

          # Restart service
          sudo systemctl restart clickfix
EOF
